### ISSUE TITLE
English or Portuguese? Or both?

### ISSUE THREAD

**Issue by raphaelfabeni** [raphaelfabeni/snippets-wp#1]
It was a doubt since the beginning of the project. I chose the English but I still think that Portuguese it is the best option for the first version.

**Comment by hussani** [comment]
It's a good question.
Who is your target people? If global, english. If local, portuguese.

Think about the work to translate any valuable release, both at portuguese as for english.

**Comment by raphaelfabeni** [comment]
First, I thought that posts in English it was the best decision. I posted on a Facebook group and I guy said about the people (portuguese) that are starting at web carrer and they may have difficulty in English.

He and another guy even suggested the project support both languages, but I have not started thinking about how to do this with Jekyll. And the thing that worries me most in both languages, is the possible difficulty in post new snippets because you always must post in English and Portuguese.

So at first I decided to keep the posts in Portuguese and in time, think of a way to leave the site in 2 languages ​​but in a way that contribute a new post be easy.
